### PR TITLE
Hi Leo I noticed some mistakes in your code - just being a helpful person (as usual). Update settings.json

### PR DESCRIPTION
**Pull request by dkol123**

### CODE REVIEW

**Comment by Andallfor** [comment]
bad

**Comment by dkol123** [comment]
Hi there respond

**Comment by dkol123** [comment]
I can't respect someone who doesn't admit their faults

**Comment by dkol123** [comment]
We all have work to do to improve ourselves

**Comment by dkol123** [comment]
It is far easier to criticize others than to recognize your own flaws.

**Pull request closed without merging**
